import Image from "next/image";
import Head from "next/head";
import { BsFillMoonStarsFill } from "react-icons/bs";
import { AiFillLinkedin } from "react-icons/ai";
import deveskinder from "./file.png";
import Git1 from "./git1.png";
import Git2 from "./git2.png";
import Git3 from "./git3.png";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Eskinder Fitsum Portfolio</title>
        <meta name="description" content="Generated by creator" />
        <link rel="icon" href="/next.svg" />
      </Head>

      <main className="bg-white px-10">
        <section className="min-h-screen">
          <nav className="py-10 mb-12 flex justify-between items-center">
            <h1 className="text-xl font-league-spartan">DevelopedByEskinder</h1>
            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill className="cursor-pointer text-2xl" />
              </li>
              <li>
                <a
                  className="bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8"
                  href="#"
                >
                  Resume
                </a>
              </li>
            </ul>
          </nav>
          <div className="text-center p-10">
            <h2 className="text-5xl py-2 text-teal-600 font-medium">
              Eskinder Fitsum
            </h2>
            <h3 className="text-2xl py-2">Developer</h3>
            <p className="text-md py-5 leading-8 text-gray-800">
              A 4th year Computer Science student at Illinois Institute of
              Technology. My interests are Artificial Intelligence, Machine
              Learning, Natural Language Processing, Software Security, Runtime
              Systems, Language Extensibility, and Computer Architecture. I also
              love to collaborate on projects; if you do as well, reach out.
            </p>
          </div>
          <div className="text-5xl flex justify-center gap-16 py-3 text-gray-600">
            <AiFillLinkedin />
          </div>
          <div className="relative mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 mt-10 overflow-hidden">
            <Image
              src={deveskinder}
              alt="Eskinder Fitsum"
              layout="fill"
              objectFit="cover"
            />
          </div>
        </section>
        <section>
          <div>
            <h3 className="text-3xl py-1">Work I've Done</h3>
            <p className="text-md py-2 leading-8 text-gray-800">
              I started learning computer science concepts in 2018 and have been
              entranced ever since. Here is some of the work I've done.
            </p>
          </div>
        </section>
        <section>
          <div>
            <h3 className="text-3xl py-1">Work I've Done</h3>
            <p className="text-md py-2 leading-8 text-gray-800">
              I started learning computer science concepts in 2018 and have been
              entranced ever since. Here is some of the work I've done.
            </p>
          </div>
        </section>
        <section>
          <div>
            <h3 className="text-3xl py-1">Work I've Done</h3>
            <p className="text-md py-2 leading-8 text-gray-800">
              I started learning computer science concepts in 2018 and have been
              entranced ever since. Here is some of the work I've done.
            </p>
          </div>
        </section>
        <section className="text-center mt-10">
          <div className="text-5xl font-extrabold mb-4">
            <span className="bg-clip-text text-transparent bg-gradient-to-r from-pink-500 to-violet-500">
              Hello World
            </span>
          </div>
          <div className="space-x-4">
            <button className="transition ease-in-out delay-150 bg-blue-500 hover:-translate-y-1 hover:scale-110 hover:bg-indigo-500 duration-300 px-4 py-2 rounded-md text-white">
              Save Changes
            </button>
            <button className="transition duration-150 ease-in-out px-4 py-2 rounded-md bg-gray-200 hover:bg-gray-300">
              Button A
            </button>
            <button className="transition duration-300 ease-in-out px-4 py-2 rounded-md bg-gray-200 hover:bg-gray-300">
              Button B
            </button>
            <button className="transition duration-700 ease-in-out px-4 py-2 rounded-md bg-gray-200 hover:bg-gray-300">
              Button C
            </button>
          </div>
          <div class="columns-3xs ...">
            <img class="w-full aspect-video" src={Git1} />
            <img class="w-full aspect-square" src={Git2} />
            <img class="w-full aspect-video" src={Git3} />
          </div>
        </section>
      </main>
    </div>
  );
}
