import Image from "next/image";
import Head from "next/head";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Eskinder Fitsum Portfolio</title>
        <meta name="description" content="Generated by creator" />
        <link rel="icon" href="/next.svg" />
      </Head>

      <main>
        <section className=" bg-blue-700 min-h-screen">
          <h1>Hello</h1>
        </section>
      </main>
    </div>
  );
}
